global using Microsoft.AspNetCore.Mvc;
global using MediatR;
global using Remote.Shell.Interrupt.SSHExecutor.AppLogger;
global using Remote.Shell.Interrupt.SSHExecutor.CommandExecutor;
global using Remote.Shell.Interrupt.SSHExecutor.Application;
global using Serilog;
global using System.Net;
global using Remote.Shell.Interrupt.SSHExecutor.Application.Features.SSHExecutor.Commands;
global using Remote.Shell.Interrupt.SSHExecutor.Application.DTOs;