global using Mapster;
global using MapsterMapper;
global using FluentValidation;
global using Mediator;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.DependencyInjection;
global using Remote.Shell.Interrupt.Storehouse.Application.Behaviors;
// Namespace ALIAS (not a type alias - this compiler doesn't support C#12's generic
// using-alias syntax) for our own CQRS contracts. Mediator ships its own generic
// CQRS.ICommand<T>/CQRS.IQuery<T>/CQRS.ICommandHandler<,>/CQRS.IQueryHandler<,> marker interfaces, which
// collide by name with ours - every reference to our own versions goes through this
// "CQRS." prefix (see Features/**) instead of relying on an unqualified name.
global using CQRS = Remote.Shell.Interrupt.Storehouse.Application.Contracts.CQRS;
global using Remote.Shell.Interrupt.Storehouse.Application.Contracts.Logger;
global using Remote.Shell.Interrupt.Storehouse.Application.Exceptions;
global using Remote.Shell.Interrupt.Storehouse.Application.Helpers;
global using Remote.Shell.Interrupt.Storehouse.Application.Middleware;
global using Remote.Shell.Interrupt.Storehouse.Domain.Common;
global using Remote.Shell.Interrupt.Storehouse.Domain.Gateway;
global using Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort;
global using Remote.Shell.Interrupt.Storehouse.Domain.SNMP;
global using System.Diagnostics;
global using System.Reflection;
global using System.Text;
global using System.Text.Json;
global using ApplicationException = Remote.Shell.Interrupt.Storehouse.Application.Exceptions.ApplicationException;
global using ValidationException = Remote.Shell.Interrupt.Storehouse.Application.Exceptions.ValidationException;
global using System.ComponentModel;
global using Remote.Shell.Interrupt.Storehouse.Domain.VirtualNetwork;
global using System.Net;
global using Microsoft.Extensions.Configuration;
global using Remote.Shell.Interrupt.Storehouse.Domain.Organization;
global using Remote.Shell.Interrupt.Storehouse.Application.DTOs.Gates;
global using Remote.Shell.Interrupt.Storehouse.Application.DTOs.Organizations;
global using Remote.Shell.Interrupt.Storehouse.Application.DTOs.TfPlans;
global using Remote.Shell.Interrupt.Storehouse.Application.DTOs.NetworkDevices;
global using Remote.Shell.Interrupt.Storehouse.Application.Contracts.Repositories.NetDevRep;
global using Remote.Shell.Interrupt.Storehouse.Application.Contracts.Repositories.LocBillRep;
global using Remote.Shell.Interrupt.Storehouse.Application.Contracts.Repositories.RemBillRep;
global using Remote.Shell.Interrupt.Storehouse.Application.Contracts.Repositories.UnOfWrkRep;
global using Remote.Shell.Interrupt.Storehouse.Application.Contracts.Repositories.GenericRep;
global using Remote.Shell.Interrupt.Storehouse.Application.Contracts.Repositories.IGateRep;
global using Remote.Shell.Interrupt.Storehouse.Application.Contracts.Repositories.SNMPRep;
global using Remote.Shell.Interrupt.Storehouse.Application.DTOs.Vlans;
global using Remote.Shell.Interrupt.Storehouse.Application.DTOs.Ports;
global using System.Linq.Expressions;
global using Remote.Shell.Interrupt.Storehouse.Application.Contracts.Repositories.Specification;
global using Remote.Shell.Interrupt.Storehouse.Application.Models.Request;
global using Remote.Shell.Interrupt.Storehouse.Application.Contracts.Repositories.QueryFilterParser;
global using Remote.Shell.Interrupt.Storehouse.Application.Helpers.Extensions;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Organizations.Queries.GetClientsByVlanTag;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.NetworkDevices.Commands.DeleteNetworkDeviceById;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.SNMPExecutor.Commands.SNMPGet;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.SNMPExecutor.Commands.SNMPWalk;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Gates.Commands.UpdateGate;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Gates.Commands.CreateGate;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.SPRVlans.Queries.GetSPRVlansByFilter;
global using Remote.Shell.Interrupt.Storehouse.Application.Models.Response;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Core.Queries;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Core.Commands;
global using Remote.Shell.Interrupt.Storehouse.Application.Models.Factories;
global using System.Text.RegularExpressions;
global using Remote.Shell.Interrupt.Storehouse.Domain.Workflow;
global using Remote.Shell.Interrupt.Storehouse.Application.Contracts.Workflow;
global using Remote.Shell.Interrupt.Storehouse.Application.Contracts.Repositories.IWorkflowRep;
global using Remote.Shell.Interrupt.Storehouse.Application.DTOs.Workflows;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Workflows.Commands.CreateWorkflow;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Workflows.Commands.UpdateWorkflow;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Workflows.Commands.DeleteWorkflow;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Workflows.Commands.ExecuteWorkflow;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Workflows.Queries.GetWorkflowsByFilter;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Workflows.Queries.GetWorkflowById;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Workflows.Commands.PublishWorkflow;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Workflows.Seed;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Workflows.Commands.ArchiveWorkflow;
global using Remote.Shell.Interrupt.Storehouse.Application.Features.Diagnostics.Commands.ReportClientError;