global using FluentValidation;
global using MediatR;
global using Microsoft.AspNetCore.Http;
global using Remote.Shell.Interrupt.BuildingBlocks.CQRS;
global using Remote.Shell.Interrupt.BuildingBlocks.Exceptions;
global using Remote.Shell.Interrupt.BuildingBlocks.Logger;
global using System.Diagnostics;
global using System.Text.Json;
global using ApplicationException = Remote.Shell.Interrupt.BuildingBlocks.Exceptions.ApplicationException;
global using ValidationException = Remote.Shell.Interrupt.BuildingBlocks.Exceptions.ValidationException;
