global using Remote.Shell.Interrupt.Storehouse.Application.Contracts;
global using Remote.Shell.Interrupt.Storehouse.Domain.Common;
global using Microsoft.Extensions.DependencyInjection;
global using MongoDB.Driver;
global using Remote.Shell.Interrupt.Storehouse.Persistence.Configuration;
global using Remote.Shell.Interrupt.Storehouse.Persistence.Repositories;
global using Remote.Shell.Interrupt.Storehouse.Domain.Gateway;
global using Remote.Shell.Interrupt.Storehouse.Domain.BusinessLogic;
global using Remote.Shell.Interrupt.Storehouse.Domain.Entity;