global using Serilog;
global using Remote.Shell.Interrupt.SNMPExecutor.Application;
global using Remote.Shell.Interrupt.SNMPExecutor.AppLogger;
global using Remote.Shell.Interrupt.SNMPExecutor.SNMPCommandExecutor;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using System.Net;
global using Remote.Shell.Interrupt.SNMPExecutor.Application.DTOs;
global using Remote.Shell.Interrupt.SNMPExecutor.Application.Features.SNMPExecutor.Commands;