global using Microsoft.Extensions.DependencyInjection;
global using Remote.Shell.Interrupt.SNMPExecutor.Application.Contracts.CommandExecutor;
global using EonaCat.Snmp.Helpers.Snmp;
global using EonaCat.Snmp.Models.Types;
global using Remote.Shell.Interrupt.BuildingBlocks.Exceptions;
global using Remote.Shell.Interrupt.SNMPExecutor.Application.Exceptions;
global using System.Text;
global using System.Text.Json.Nodes;
global using EonaCat.Snmp.Extensions;