CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" uuid NOT NULL,
        "FullName" text,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "CODs" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "IdCOD" integer NOT NULL,
        "NameCOD" text NOT NULL,
        "Telephone" text,
        "Email1" text,
        "Email2" text,
        "Contact" text,
        "Description" text,
        "Region" text,
        "CreatedAt" timestamptz NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamptz,
        CONSTRAINT "PK_CODs" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_CODs_IdCOD" UNIQUE ("IdCOD")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "Gates" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Name" text NOT NULL,
        "IPAddress" bigint NOT NULL,
        "Community" text NOT NULL,
        "TypeOfNetworkDevice" integer NOT NULL,
        "CreatedAt" timestamptz NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamptz,
        CONSTRAINT "PK_Gates" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "NetworkDevices" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Host" bigint NOT NULL,
        "TypeOfNetworkDevice" integer NOT NULL,
        "NetworkDeviceName" text NOT NULL,
        "GeneralInformation" text NOT NULL,
        "CreatedAt" timestamptz NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamptz,
        CONSTRAINT "PK_NetworkDevices" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "TfPlans" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "IdTfPlan" integer NOT NULL,
        "NameTfPlan" text NOT NULL,
        "DescTfPlan" text NOT NULL,
        "CreatedAt" timestamptz NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamptz,
        CONSTRAINT "PK_TfPlans" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_TfPlans_IdTfPlan" UNIQUE ("IdTfPlan")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "VLANs" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "VLANTag" integer NOT NULL,
        "VLANName" text NOT NULL,
        "CreatedAt" timestamptz NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamptz,
        CONSTRAINT "PK_VLANs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "Ports" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "InterfaceNumber" integer NOT NULL,
        "InterfaceName" text NOT NULL,
        "InterfaceType" integer NOT NULL,
        "InterfaceStatus" integer NOT NULL,
        "InterfaceSpeed" bigint NOT NULL,
        "MACAddress" text NOT NULL,
        "Description" text NOT NULL,
        "ParentId" uuid,
        "NetworkDeviceId" uuid NOT NULL,
        "CreatedAt" timestamptz NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamptz,
        CONSTRAINT "PK_Ports" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Ports_NetworkDevices_NetworkDeviceId" FOREIGN KEY ("NetworkDeviceId") REFERENCES "NetworkDevices" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Ports_Ports_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Ports" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "Clients" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "IdClient" integer NOT NULL,
        "Dat1" timestamptz,
        "Dat2" timestamptz,
        "Prim1" text,
        "Prim2" text,
        "Nik" text,
        "NrDogovor" text NOT NULL DEFAULT 'unknown',
        "Name" text NOT NULL,
        "ContactC" text,
        "TelephoneC" text,
        "ContactT" text,
        "TelephoneT" text,
        "EmailC" text,
        "Working" boolean NOT NULL,
        "EmailT" text,
        "History" text,
        "AntiDDOS" boolean NOT NULL,
        "Id_COD" integer NOT NULL,
        "Id_TfPlan" integer,
        "CreatedAt" timestamptz NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamptz,
        CONSTRAINT "PK_Clients" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_Clients_IdClient" UNIQUE ("IdClient"),
        CONSTRAINT "FK_Clients_CODs_Id_COD" FOREIGN KEY ("Id_COD") REFERENCES "CODs" ("IdCOD") ON DELETE CASCADE,
        CONSTRAINT "FK_Clients_TfPlans_Id_TfPlan" FOREIGN KEY ("Id_TfPlan") REFERENCES "TfPlans" ("IdTfPlan")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "ARPEntities" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "MAC" text NOT NULL,
        "IPAddress" text NOT NULL,
        "PortId" uuid NOT NULL,
        "CreatedAt" timestamptz NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamptz,
        CONSTRAINT "PK_ARPEntities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ARPEntities_Ports_PortId" FOREIGN KEY ("PortId") REFERENCES "Ports" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "MACEntities" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "MACAddress" text NOT NULL,
        "PortId" uuid NOT NULL,
        "CreatedAt" timestamptz NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamptz,
        CONSTRAINT "PK_MACEntities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MACEntities_Ports_PortId" FOREIGN KEY ("PortId") REFERENCES "Ports" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "PortVLAN" (
        "PortsId" uuid NOT NULL,
        "VLANsId" uuid NOT NULL,
        CONSTRAINT "PK_PortVLAN" PRIMARY KEY ("PortsId", "VLANsId"),
        CONSTRAINT "FK_PortVLAN_Ports_PortsId" FOREIGN KEY ("PortsId") REFERENCES "Ports" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PortVLAN_VLANs_VLANsId" FOREIGN KEY ("VLANsId") REFERENCES "VLANs" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "TerminatedNetworkEntities" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "NetworkAddress" bigint NOT NULL,
        "Netmask" bigint NOT NULL,
        "PortId" uuid NOT NULL,
        "CreatedAt" timestamptz NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamptz,
        CONSTRAINT "PK_TerminatedNetworkEntities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TerminatedNetworkEntities_Ports_PortId" FOREIGN KEY ("PortId") REFERENCES "Ports" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE TABLE "SPRVlans" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "IdVlan" integer NOT NULL,
        "IdClient" integer NOT NULL,
        "UseClient" boolean NOT NULL,
        "UseCOD" boolean NOT NULL,
        "CreatedAt" timestamptz NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamptz,
        CONSTRAINT "PK_SPRVlans" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SPRVlans_Clients_IdClient" FOREIGN KEY ("IdClient") REFERENCES "Clients" ("IdClient") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_ARPEntities_PortId" ON "ARPEntities" ("PortId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_Clients_Id_COD" ON "Clients" ("Id_COD");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_Clients_Id_TfPlan" ON "Clients" ("Id_TfPlan");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE UNIQUE INDEX "IX_Clients_IdClient" ON "Clients" ("IdClient");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE UNIQUE INDEX "IX_CODs_IdCOD" ON "CODs" ("IdCOD");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_Gates_IPAddress" ON "Gates" ("IPAddress");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_MACEntities_PortId" ON "MACEntities" ("PortId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_Ports_NetworkDeviceId" ON "Ports" ("NetworkDeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_Ports_ParentId" ON "Ports" ("ParentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_PortVLAN_VLANsId" ON "PortVLAN" ("VLANsId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_SPRVlans_IdClient" ON "SPRVlans" ("IdClient");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_SPRVlans_IdVlan" ON "SPRVlans" ("IdVlan");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_TerminatedNetworkEntities_PortId" ON "TerminatedNetworkEntities" ("PortId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE UNIQUE INDEX "IX_TfPlans_IdTfPlan" ON "TfPlans" ("IdTfPlan");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    CREATE INDEX "IX_VLANs_VLANTag" ON "VLANs" ("VLANTag");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906215217_InitialIdentitySetup') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260906215217_InitialIdentitySetup', '9.0.4');
    END IF;
END $EF$;
COMMIT;

