// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Remote.Shell.Interrupt.Storehouse.Dapper.Persistence.Configuration;

#nullable disable

namespace Remote.Shell.Interrupt.Storehouse.Dapper.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PortVLAN", b =>
                {
                    b.Property<Guid>("PortsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VLANsId")
                        .HasColumnType("uuid");

                    b.HasKey("PortsId", "VLANsId");

                    b.HasIndex("VLANsId");

                    b.ToTable("PortVLAN", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Dapper.Persistence.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Dapper.Persistence.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ExpiresAtUtc");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("ReplacedByTokenHash");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("RevokedAtUtc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TokenHash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Gateway.Gate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Community")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Community");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("IPAddress")
                        .HasColumnType("bigint")
                        .HasColumnName("IPAddress");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int>("TypeOfNetworkDevice")
                        .HasColumnType("integer")
                        .HasColumnName("TypeOfNetworkDevice");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IPAddress");

                    b.ToTable("Gates", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Gateway.NetworkDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GeneralInformation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("GeneralInformation");

                    b.Property<long>("Host")
                        .HasColumnType("bigint")
                        .HasColumnName("Host");

                    b.Property<string>("NetworkDeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeOfNetworkDevice")
                        .HasColumnType("integer")
                        .HasColumnName("TypeOfNetworkDevice");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("NetworkDevices", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.ARPEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IPAddress");

                    b.Property<string>("MAC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MAC");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uuid")
                        .HasColumnName("PortId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.ToTable("ARPEntities", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.MACEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MACAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MACAddress");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uuid")
                        .HasColumnName("PortId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.ToTable("MACEntities", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.Port", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("InterfaceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("InterfaceName");

                    b.Property<int>("InterfaceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("InterfaceNumber");

                    b.Property<long>("InterfaceSpeed")
                        .HasColumnType("bigint")
                        .HasColumnName("InterfaceSpeed");

                    b.Property<int>("InterfaceStatus")
                        .HasColumnType("integer")
                        .HasColumnName("InterfaceStatus");

                    b.Property<int>("InterfaceType")
                        .HasColumnType("integer")
                        .HasColumnName("InterfaceType");

                    b.Property<string>("MACAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MACAddress");

                    b.Property<Guid>("NetworkDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("NetworkDeviceId");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("ParentId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("NetworkDeviceId");

                    b.HasIndex("ParentId");

                    b.ToTable("Ports", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.TerminatedNetworkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("Netmask")
                        .HasColumnType("bigint")
                        .HasColumnName("Netmask");

                    b.Property<long>("NetworkAddress")
                        .HasColumnType("bigint")
                        .HasColumnName("NetworkAddress");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uuid")
                        .HasColumnName("PortId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.ToTable("TerminatedNetworkEntities", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Organization.COD", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Contact")
                        .HasColumnType("text")
                        .HasColumnName("Contact");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("Email1")
                        .HasColumnType("text")
                        .HasColumnName("Email1");

                    b.Property<string>("Email2")
                        .HasColumnType("text")
                        .HasColumnName("Email2");

                    b.Property<int>("IdCOD")
                        .HasColumnType("integer")
                        .HasColumnName("IdCOD");

                    b.Property<string>("NameCOD")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NameCOD");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("Region");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("Telephone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IdCOD")
                        .IsUnique();

                    b.ToTable("CODs", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Organization.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AntiDDOS")
                        .HasColumnType("boolean")
                        .HasColumnName("AntiDDOS");

                    b.Property<string>("ContactC")
                        .HasColumnType("text")
                        .HasColumnName("ContactC");

                    b.Property<string>("ContactT")
                        .HasColumnType("text")
                        .HasColumnName("ContactT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Dat1")
                        .HasColumnType("timestamptz")
                        .HasColumnName("Dat1");

                    b.Property<DateTime?>("Dat2")
                        .HasColumnType("timestamptz")
                        .HasColumnName("Dat2");

                    b.Property<string>("EmailC")
                        .HasColumnType("text")
                        .HasColumnName("EmailC");

                    b.Property<string>("EmailT")
                        .HasColumnType("text")
                        .HasColumnName("EmailT");

                    b.Property<string>("History")
                        .HasColumnType("text")
                        .HasColumnName("History");

                    b.Property<int>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("IdClient");

                    b.Property<int>("Id_COD")
                        .HasColumnType("integer")
                        .HasColumnName("Id_COD");

                    b.Property<int?>("Id_TfPlan")
                        .HasColumnType("integer")
                        .HasColumnName("Id_TfPlan");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Nik")
                        .HasColumnType("text")
                        .HasColumnName("Nik");

                    b.Property<string>("NrDogovor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("unknown")
                        .HasColumnName("NrDogovor");

                    b.Property<string>("Prim1")
                        .HasColumnType("text")
                        .HasColumnName("Prim1");

                    b.Property<string>("Prim2")
                        .HasColumnType("text")
                        .HasColumnName("Prim2");

                    b.Property<string>("TelephoneC")
                        .HasColumnType("text")
                        .HasColumnName("TelephoneC");

                    b.Property<string>("TelephoneT")
                        .HasColumnType("text")
                        .HasColumnName("TelephoneT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<bool>("Working")
                        .HasColumnType("boolean")
                        .HasColumnName("Working");

                    b.HasKey("Id");

                    b.HasIndex("IdClient")
                        .IsUnique();

                    b.HasIndex("Id_COD");

                    b.HasIndex("Id_TfPlan");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Organization.SPRVlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("IdClient");

                    b.Property<int>("IdVlan")
                        .HasColumnType("integer")
                        .HasColumnName("IdVlan");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<bool>("UseCOD")
                        .HasColumnType("boolean")
                        .HasColumnName("UseCOD");

                    b.Property<bool>("UseClient")
                        .HasColumnType("boolean")
                        .HasColumnName("UseClient");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdVlan");

                    b.ToTable("SPRVlans", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Organization.TfPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DescTfPlan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DescTfPlan");

                    b.Property<int>("IdTfPlan")
                        .HasColumnType("integer")
                        .HasColumnName("IdTfPlan");

                    b.Property<string>("NameTfPlan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NameTfPlan");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IdTfPlan")
                        .IsUnique();

                    b.ToTable("TfPlans", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.VirtualNetwork.VLAN", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("VLANName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VLANName");

                    b.Property<int>("VLANTag")
                        .HasColumnType("integer")
                        .HasColumnName("VLANTag");

                    b.HasKey("Id");

                    b.HasIndex("VLANTag");

                    b.ToTable("VLANs", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Workflow.EdgeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Condition")
                        .HasColumnType("text")
                        .HasColumnName("Condition");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("FromNodeId");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("Priority");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("ToNodeId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowDefinitionId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("WorkflowEdges", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Workflow.NodeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Config");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("Key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("PositionX");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("PositionY");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowDefinitionId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("WorkflowNodes", (string)null);
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Workflow.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<Guid>("StartNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("StartNodeId");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WorkflowDefinitions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Dapper.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Dapper.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Dapper.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Dapper.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortVLAN", b =>
                {
                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.Port", null)
                        .WithMany()
                        .HasForeignKey("PortsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Domain.VirtualNetwork.VLAN", null)
                        .WithMany()
                        .HasForeignKey("VLANsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Dapper.Persistence.Identity.RefreshToken", b =>
                {
                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Dapper.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.ARPEntity", b =>
                {
                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.Port", null)
                        .WithMany("ARPTableOfInterface")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.MACEntity", b =>
                {
                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.Port", null)
                        .WithMany("MACTable")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.Port", b =>
                {
                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Domain.Gateway.NetworkDevice", null)
                        .WithMany("PortsOfNetworkDevice")
                        .HasForeignKey("NetworkDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.Port", null)
                        .WithMany("AggregatedPorts")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.TerminatedNetworkEntity", b =>
                {
                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.Port", null)
                        .WithMany("NetworkTableOfInterface")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Organization.Client", b =>
                {
                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Domain.Organization.COD", "COD")
                        .WithMany()
                        .HasForeignKey("Id_COD")
                        .HasPrincipalKey("IdCOD")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Domain.Organization.TfPlan", "TfPlan")
                        .WithMany()
                        .HasForeignKey("Id_TfPlan")
                        .HasPrincipalKey("IdTfPlan");

                    b.Navigation("COD");

                    b.Navigation("TfPlan");
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Organization.SPRVlan", b =>
                {
                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Domain.Organization.Client", null)
                        .WithMany("SPRVlans")
                        .HasForeignKey("IdClient")
                        .HasPrincipalKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Workflow.EdgeDefinition", b =>
                {
                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Domain.Workflow.WorkflowDefinition", null)
                        .WithMany("Edges")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Workflow.NodeDefinition", b =>
                {
                    b.HasOne("Remote.Shell.Interrupt.Storehouse.Domain.Workflow.WorkflowDefinition", null)
                        .WithMany("Nodes")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Gateway.NetworkDevice", b =>
                {
                    b.Navigation("PortsOfNetworkDevice");
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.InterfacePort.Port", b =>
                {
                    b.Navigation("ARPTableOfInterface");

                    b.Navigation("AggregatedPorts");

                    b.Navigation("MACTable");

                    b.Navigation("NetworkTableOfInterface");
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Organization.Client", b =>
                {
                    b.Navigation("SPRVlans");
                });

            modelBuilder.Entity("Remote.Shell.Interrupt.Storehouse.Domain.Workflow.WorkflowDefinition", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
